Exploration of showing training adviser within the application
DFE-Digital/apply-for-teacher-training-prototype pull request #608
Opened 2021-12-10 15:30 UTC by frankieroberto

Currently we link to the "Get an adviser" service at several points within the application and after submission, as we know that teacher training advisers are often able to help support candidates with some of the stumbling blocks within the process.

However, we don’t currently know whether the candidate already has a teacher training adviser assigned. This means that the text is often vague to cover both scenarios, for example "speak to a teacher training adviser" – but the link still goes to the Get an adviser service, which is less helpful if the candidate already has one.

If we could tell wither the candidate had an adviser, we could:

* make the call to action to **get an adviser** stronger, if we know they don't have one
* remind candidates of the name and email address of their adviser, if they have one

Below is an exploration of how this might work in 3 of the places we currently link to the Get an adviser service.

## Personal statement

### Current

<img width="710" alt="Screenshot 2021-12-10 at 15 19 15" src="https://user-images.githubusercontent.com/30665/145597796-4846ff7d-7df4-4d46-9106-304b676557ed.png">

### Future: with no adviser
 
<img width="698" alt="Screenshot 2021-12-10 at 15 20 44" src="https://user-images.githubusercontent.com/30665/145597819-b5823ac6-fd1a-49cc-9f2c-91dfc944fa20.png">

### Future: with an adviser

<img width="706" alt="Screenshot 2021-12-10 at 15 21 42" src="https://user-images.githubusercontent.com/30665/145597878-6f8384af-83b3-4b97-a0ca-c5a4c167346c.png">

## GCSE equivalencies

### Current

<img width="700" alt="Screenshot 2021-12-10 at 15 22 48" src="https://user-images.githubusercontent.com/30665/145598053-3da8bf6e-1325-4e33-9ed8-804ee303403d.png">

### Future: with no adviser

<img width="666" alt="Screenshot 2021-12-10 at 15 24 26" src="https://user-images.githubusercontent.com/30665/145598304-d3cfd37d-ee90-42cc-a385-f3cb218476e0.png">

### Future: with an adviser

<img width="691" alt="Screenshot 2021-12-10 at 15 24 52" src="https://user-images.githubusercontent.com/30665/145598355-f9e0f0d5-6578-448f-8e0e-2b352643f62d.png">

## Unsuccessful with an application

### Current

<img width="702" alt="Screenshot 2021-12-10 at 15 25 35" src="https://user-images.githubusercontent.com/30665/145598479-a77dcaf9-8d11-4ef8-a808-20152c99b381.png">

### Future: with no adviser

<img width="733" alt="Screenshot 2021-12-10 at 15 26 11" src="https://user-images.githubusercontent.com/30665/145598575-59470cc1-4d21-4ec6-8f76-d76aa9a6ad3d.png">

### Future: with an adviser

<img width="732" alt="Screenshot 2021-12-10 at 15 26 35" src="https://user-images.githubusercontent.com/30665/145598647-0ee80d62-f071-4ba4-8694-8fb94fca8079.png">

2022-01-04 11:19 UTC, EmmaFrith commented on app/views/application/gcse/equivalency.html
> +    <p class="govuk-body">Contact your chosen provider or your adviser Bob for advice: <br><a href="#" class="govuk-link">bob.jones@ta-recruit.education.gov.uk</a></p>
```suggestion
    <p class="govuk-body">Contact your teacher training provider or your adviser Bob for advice: <br><a href="#" class="govuk-link">bob.jones@ta-recruit.education.gov.uk</a></p>
```

2022-01-04 11:19 UTC, EmmaFrith commented on app/views/application/gcse/equivalency.html
> +    <p class="govuk-body">For advice, contact your chosen training provider or <a href="https://adviser-getintoteaching.education.gov.uk" class="govuk-link">get a teacher training adviser</a>.</p>
```suggestion
    <p class="govuk-body">For advice, contact your teacher training provider or <a href="https://adviser-getintoteaching.education.gov.uk" class="govuk-link">get a teacher training adviser</a>.</p>
```

2022-01-04 11:29 UTC, EmmaFrith commented on app/views/application/personal-statement/index.html
> +      <p class="govuk-body">Speak to your adviser Bob for support in answering this question: <br><a href="#" class="govuk-link">bob.jones@ta-recrit.education.gov.uk</a>
```suggestion
      <p class="govuk-body">Contact your teacher training adviser Bob at <br><a href="#" class="govuk-link">bob.jones@ta-recrit.education.gov.uk</a> for support in answering this question.</p>
```

2022-01-04 11:41 UTC, EmmaFrith commented on app/views/application/gcse/equivalency.html
>    <p class="govuk-body">Some providers may let you sit an equivalency test to show you have the required skills.</p>
```suggestion
  <p class="govuk-body">Some providers may let you do an equivalency test to show you have the required skills.</p>
```

2022-01-04 11:42 UTC, EmmaFrith commented on app/views/dashboard/_apply-again.html
>    <p class="govuk-body">If now’s the right time, you can still apply for courses that start this academic year.</p>
```suggestion
  <p class="govuk-body">If now’s the right time for you, you can still apply for courses that start this academic year.</p>
```

2022-01-04 11:45 UTC, EmmaFrith commented on app/views/dashboard/_apply-again.html
> +      To talk about your options, <a href="https://beta-adviser-getintoteaching.education.gov.uk/">get a teacher training adviser</a>.
```suggestion
      <a href="https://beta-adviser-getintoteaching.education.gov.uk/">Get a teacher training adviser</a> to talk about your options.
```

2022-01-04 11:56 UTC, EmmaFrith commented on app/views/dashboard/_apply-again.html
> +      You can talk about your options with your adviser Bob: <br><a href="#">bob.jones@ta-recruit.education.gov.uk</a>.
```suggestion
      Contact your teacher training adviser Bob: <br><a href="#">bob.jones@ta-recruit.education.gov.uk</a> to talk about your options.
```

2022-01-04 11:57 UTC, EmmaFrith requested changes
Hey @frankieroberto, love this idea. Have suggested a few copy change suggestions. We can look at the copy again together if we end up implementing this.

2022-08-09 07:49 UTC, MylesJarvis commented
Closing for now.

2022-08-09 07:49 UTC, closed without merging